org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=false
android.jetifier.ignorelist = C:\Users\abdis\.gradle\caches\modules-2\files-2.1\io.flutter\arm64_v8a_debug\1.0.0-ef0cd000916d64fa0c5d09cc809fa7ad244a5767\cc72918ea3e799c68763351a88a07ce1fa020b3f\arm64_v8a_debug-1.0.0-ef0cd000916d64fa0c5d09cc809fa7ad244a5767.jar