// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7FTbwzuZOl2tBXpJD5a22_7TIdTLErh8',
    appId: '1:379960841880:web:f853ed4b91073b9063a2ed',
    messagingSenderId: '379960841880',
    projectId: 'chat-app-d265d',
    authDomain: 'chat-app-d265d.firebaseapp.com',
    storageBucket: 'chat-app-d265d.firebasestorage.app',
    measurementId: 'G-4C5LXYBSJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwxTCxcabY41rDX7St91iz2l-bgQ6a8rk',
    appId: '1:379960841880:android:5165e566fc3c79d463a2ed',
    messagingSenderId: '379960841880',
    projectId: 'chat-app-d265d',
    storageBucket: 'chat-app-d265d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCVSQcn_0gllFZfEZZ324OlTkYdn9Xg5Y',
    appId: '1:379960841880:ios:11ca2bfc1138a2b763a2ed',
    messagingSenderId: '379960841880',
    projectId: 'chat-app-d265d',
    storageBucket: 'chat-app-d265d.firebasestorage.app',
    iosBundleId: 'com.example.chatifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCVSQcn_0gllFZfEZZ324OlTkYdn9Xg5Y',
    appId: '1:379960841880:ios:11ca2bfc1138a2b763a2ed',
    messagingSenderId: '379960841880',
    projectId: 'chat-app-d265d',
    storageBucket: 'chat-app-d265d.firebasestorage.app',
    iosBundleId: 'com.example.chatifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7FTbwzuZOl2tBXpJD5a22_7TIdTLErh8',
    appId: '1:379960841880:web:df6ba9bbec359c9563a2ed',
    messagingSenderId: '379960841880',
    projectId: 'chat-app-d265d',
    authDomain: 'chat-app-d265d.firebaseapp.com',
    storageBucket: 'chat-app-d265d.firebasestorage.app',
    measurementId: 'G-7BSGHQ7H6W',
  );

}